- name: Install Nginx
  hosts: all
  become: true  # Run tasks with sudo (root) privileges

  tasks:
    - name: Install Nginx package
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

  # vars:
  #   ansible_ssh_private_key_file: /home/runner/.ssh/id_rsa

