- name: Uninstall Nginx
  hosts: all
  become: true  # Run tasks with sudo (root) privileges

  tasks:
    - name: Uninstall Nginx
      apt:
        name: nginx
        state: absent
vars:
    ansible_ssh_private_key_file: /home/runner/.ssh/id_rsa
